#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - '8.8.8.8'
    - '8.8.4.4'

packages:
  - curl
  - openssh-server
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

runcmd:
  - curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker multipass
  - curl -sSLo kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64"
  - chmod +x kind
  - mv kind /usr/local/bin/kind
  - curl -sSLO "https://storage.googleapis.com/kubernetes-release/release/v1.14.10/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - mv kubectl /usr/local/bin/kubectl
  - curl -sSL "https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz" | tar xzvf -
  - sudo mv linux-amd64/helm /usr/local/bin/helm
  - rm -rf linux-amd64


# ssh_authorized_keys:
#   - ssh-rsa ... 
