#cloud-config

## Add your public keys for easy ssh
# ssh_authorized_keys:
#   - ssh-rsa ... 

package_update: true
package_upgrade: true
package_reboot_if_required: true

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - '8.8.8.8'
    - '8.8.4.4'

packages:
  - curl
  - openssh-server
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - jq

runcmd:
  - export KIND_VERSION=0.7.0
  - export KUBECTL_VERSION=1.14.10
  - export HELM_VERSION=2.14.3
  - curl -fsSL https://get.docker.com | sudo sh -
  - systemctl enable docker && systemctl start docker
  - usermod -aG docker multipass
  - curl -sSLo /usr/local/bin/kind "https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-linux-amd64"
  - chmod +x /usr/local/bin/kind
  - curl -sSLo /usr/local/bin/kubectl "https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
  - chmod +x /usr/local/bin/kubectl
  - curl -sSL "https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz" | tar xzvf -
  - sudo mv linux-amd64/helm /usr/local/bin/helm
  - rm -rf linux-amd64
  - curl -sfL https://raw.githubusercontent.com/rancher/k3d/master/install.sh | bash
