#cloud-config

## Add your public keys for easy ssh
# ssh_authorized_keys:
#   - ssh-rsa ... 

package_update: true
package_upgrade: true
package_reboot_if_required: true

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - '8.8.8.8'
    - '8.8.4.4'

packages:
  - curl
  - openssh-server
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - jq

runcmd:
  - export MICROK8S_CHANNEL="1.14/stable"
  - snap install microk8s --classic --channel=${MICROK8S_CHANNEL}
  - usermod -aG microk8s multipass
